# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5bea84feba0fa096de08a4ac7097da2a754dc961b04ffd46ffdbdcc2a24e982964ae24b99ae5b96606fdda2360a172ac649cb61f07efbdba1cd4073505f55ed

test:
  secret_key_base: be5152089282f9458b78dffbd5d733100bda8c1099a567510515c39ced6c2a069adec9870d630052739a02bcfebdf13a20b1cfcb10c2df26a0d37cb861ecf474

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
